In [ ]:
https://www.perplexity.ai/search/cc086321-725e-4231-a50a-8d53131ab4e2

In [1]:
import pandas as pd

df = pd.read_csv('各鄉鎮市區人口密度.csv')
df

,statistic_yyy,site_id,people_total,area,population_density
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [2]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             375 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 14.8+ KB

In [3]:
df1 = df.rename(columns={'statistic_yyy':'統計年',
                  'site_id':'區域別',
                  'people_total':'年底人口數',
                  'area':'土地面積',
                  'population_density':'人口密度'
                    })
df1

,統計年,區域別,年底人口數,土地面積,人口密度
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [6]:
df2 = df1.drop(index=0)
df3 = df2.dropna(axis=0,how='any')

In [7]:
df4 = df3.drop('統計年',axis=1)
df4

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484   16.317  23747
3    新北市中和區  413590   20.144  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360      9.9    238
367  連江縣莒光鄉    1624      4.7    346
368  連江縣東引鄉    1352      3.8    356
369    東沙群島      …      2.38     …
370    南沙群島      …    0.5045     …

[370 rows x 4 columns]

In [8]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     370 non-null    object
 1   年底人口數   370 non-null    object
 2   土地面積    370 non-null    object
 3   人口密度    370 non-null    object
dtypes: object(4)
memory usage: 14.5+ KB

In [9]:
for value in df4['年底人口數']:
    print(value)

551480
387484
413590
222585
416524
302089
184149
86593
114926
169597
199321
40353
238067
201309
84919
78911
106101
23660
7683
6528
23200
12286
38493
4719
8939
12552
22015
22296
6320
206988
225753
309969
230710
159608
129278
191850
274424
122155
287771
288295
256456
440840
405216
94451
167639
161912
89281
157633
198074
121822
224219
48953
66472
11505
18450
75811
125067
115627
147653
227043
168760
274819
166879
50714
77761
86420
92645
57993
54482
65553
108288
95203
24754
15066
32185
19303
74554
57322
77818
65393
189066
211492
10949
77966
25583
28520
21365
23718
21049
44603
24239
22275
21448
9761
59380
26078
24758
22974
19849
11188
43630
48386
36574
30564
7314
14151
9717
8787
4876
75518
68424
34433
4038
233905
186841
125394
132726
192224
66496
77770
24219
139259
197072
183751
343243
51153
26991
171033
189839
28763
157475
359120
69990
112397
42757
34577
85894
44291
97329
37579
29922
7245
28844
52761
29803
30217
13980
19383
36116
36940
39973
13016
6107
12038
14540
1924
4246
3125
95918
72319
40056
29398
35777
24250
32458
53289
39673
21467
6102
5900
181955
28896
33415
96918
77444
13064
56836
20061
14550
9390
5538
9543
4559
89165
103147
45976
34691
85587
36750
17134
14738
33773
18138
10176
10840
16530
7154
12952
6756
4417
5883
233613
124632
86799
90986
33355
55686
41890
50980
16928
36957
47332
39357
45924
23755
36870
32587
34836
37334
43144
15325
27462
30642
33714
16987
15303
30060
100180
81033
97875
55060
10904
38796
17808
14842
15946
18803
17803
16253
15748
108567
44941
70892
46244
28932
40278
31708
19263
28939
18230
27255
24678
45665
14893
13010
23954
25980
23667
27653
25624
37781
42382
27143
31198
71693
14751
31935
23318
24969
18486
15577
49744
44974
35962
19475
11599
4564
5631
200452
54377
47866
30726
50935
30008
11076
22110
26459
25997
24622
20556
54707
17158
9936
24571
35321
15720
18080
10670
19380
12337
8586
7840
5478
7644
3246
6746
5271
7465
4867
4806
4926
105960
14238
8742
17399
6117
11163
8517
7260
7951
8248
3926
3551
4222
3518
3653
5075
104380
10861
24345
20185
83747
18043
12888
4383
11653
10413
15889
6384
6066
62308
14508
9817
8408
5176
3856
52163
53972
38708
44314
47908
82358
52035
212553
150636
77943
122103
147295
43285
29413
20535
30838
12700
685
7544
2360
1624
1352
…
…

In [12]:
def strToInt(x:str)->int:
    try:
        return int(x)
    except:
        return 0

df4['年底人口數'] = df4['年底人口數'].apply(strToInt)
df4['人口密度'] = df4['人口密度'].apply(strToInt)
df4['土地面積']= df4['土地面積'].astype('float')
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     370 non-null    object
 1   年底人口數   370 non-null    int64
 2   土地面積    370 non-null    float64
 3   人口密度    370 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 14.5+ KB

In [16]:
def split_area(v:str)->str:
    if len(v) >= 6:
        return v[:3]
    else:
        return v
    
def split_area1(v:str)->str:
    if len(v) >=6:
        return v[-3:]
    else:
        return v
    

df4['縣市'] = df4['區域別'].apply(split_area)
df4['區域'] = df4['區域別'].apply(split_area1)
df5 = df4.reindex(columns=['縣市','區域','年底人口數','土地面積','人口密度'])
df5.query('年底人口數>=500000')

    縣市   區域   年底人口數     土地面積   人口密度
1  新北市  板橋區  551480  23.1373  23835

In [17]:
m = df5['人口密度'].max()
df5.query('人口密度== @m')

    縣市   區域   年底人口數    土地面積   人口密度
4  新北市  永和區  222585  5.7138  38956

In [19]:
df6 = df5.groupby(by='縣市')[['年底人口數','土地面積','人口密度']].agg([('平均','mean'),('加總','sum')])
df6.columns.names= ["資料","統計"]
df6

資料             年底人口數                 土地面積                     人口密度
統計                平均       加總          平均         加總            平均      加總
縣市
南投縣     38542.384615   501051  315.879692  4106.4360    338.692308    4403
南沙群島        0.000000        0    0.504500     0.5045      0.000000       0
嘉義市東區  122103.000000   122103   30.155600    30.1556   4049.000000    4049
嘉義市西區  147295.000000   147295   29.870000    29.8700   4931.000000    4931
嘉義縣     28399.000000   511182  105.757594  1903.6367    383.666667    6906
基隆市     53065.428571   371458   18.965557   132.7589   4603.857143   32227
宜蘭縣     38050.583333   456607  178.635425  2143.6251   1125.416667   13505
屏東縣     25149.666667   829939   84.109100  2775.6003    567.666667   18733
彰化縣     49325.307692  1282458   41.322923  1074.3960   1293.307692   33626
新北市    137472.034483  3986689   70.778162  2052.5667   6697.689655  194233
新竹市     77943.000000    77943   54.849100    54.8491   1421.000000    1421
新竹市北區  150636.000000   150636   15.726700    15.7267   9578.000000    9578
新竹市東區  212553.000000   212553   33.576800    33.5768   6330.000000    6330
新竹縣     42474.538462   552169  109.810531  1427.5369    784.230769   10195
東沙群島        0.000000        0    2.380000     2.3800      0.000000       0
桃園市    168309.000000  2188017   93.919538  1220.9540   3050.153846   39652
澎湖縣     17345.500000   104073   21.144017   126.8641    689.166667    4135
臺中市     96019.250000  2304462   91.053296  2185.2791   2328.083333   55874
臺中市中區   18450.000000    18450    0.880300     0.8803  20959.000000   20959
臺中市北區  147653.000000   147653    6.937600     6.9376  21283.000000   21283
臺中市南區  125067.000000   125067    6.810100     6.8101  18365.000000   18365
臺中市東區   75811.000000    75811    9.285500     9.2855   8164.000000    8164
臺中市西區  115627.000000   115627    5.704200     5.7042  20271.000000   20271
臺北市    223604.750000  2683257   22.649975   271.7997  15377.666667  184532
臺南市     42398.852941  1441561   62.956924  2140.5354   1264.911765   43007
臺南市北區  132726.000000   132726   10.434000    10.4340  12721.000000   12721
臺南市南區  125394.000000   125394   27.268100    27.2681   4599.000000    4599
臺南市東區  186841.000000   186841   13.415600    13.4156  13927.000000   13927
臺東縣     13721.250000   219540  219.703287  3515.2526    133.375000    2134
花蓮縣     25325.923077   329237  356.043954  4628.5714    466.692308    6067
苗栗縣     30767.055556   553807  101.128606  1820.3149    571.222222   10282
連江縣      3220.000000    12880    7.200000    28.8000    416.250000    1665
金門縣     22909.333333   137456   25.276000   151.6560    932.666667    5596
雲林縣     34518.650000   690373   64.541630  1290.8326    560.050000   11201
高雄市     73076.631579  2776912   77.680326  2951.8524   5116.052632  194410

In [20]:
df6.stack(level=['資料','統計'],future_stack=True).unstack(level=['縣市','資料'])

縣市            南投縣                            南沙群島                  嘉義市東區  \
資料          年底人口數         土地面積         人口密度 年底人口數    土地面積 人口密度     年底人口數
統計
平均   38542.384615   315.879692   338.692308   0.0  0.5045  0.0  122103.0
加總  501051.000000  4106.436000  4403.000000   0.0  0.5045  0.0  122103.0

縣市                      嘉義市西區  ...      連江縣            金門縣           \
資料     土地面積    人口密度     年底人口數  ...     人口密度          年底人口數     土地面積
統計                             ...
平均  30.1556  4049.0  147295.0  ...   416.25   22909.333333   25.276
加總  30.1556  4049.0  147295.0  ...  1665.00  137456.000000  151.656

縣市                     雲林縣                                 高雄市               \
資料         人口密度      年底人口數        土地面積      人口密度         年底人口數         土地面積
統計
平均   932.666667   34518.65    64.54163    560.05  7.307663e+04    77.680326
加總  5596.000000  690373.00  1290.83260  11201.00  2.776912e+06  2951.852400

縣市
資料           人口密度
統計
平均    5116.052632
加總  194410.000000

[2 rows x 105 columns]